### ISSUE TITLE
Section needed to parse?

### ISSUE THREAD

**Issue by Somebodyisnobody** [candlepin/python-iniparse#14]
Hello, I opened an issue on WeblateOrg/weblate#5715 because my ini file could not be parsed by weblate as it contains no sections. The developers there told me that it's a problem caused by python-iniparse. I want to ask why it is needed to have sections in ini files to be able to parse them. As far as I know ini-files are specified with sections as optional element. If it's not needed I want request to remove the requirement and make it optional.

**Comment by jirihnidek** [comment]
Hi,
Interesting. The python-iniparse tries to be backward compatible with `ConfigParser`, `RawConfigParser`, and `SafeConfigParser`. Using sections is required there. Removing this requirement could break this backward compatibility and it could have unexpected side-effects in other projects. Another reason for requiring section is whole concept of accessing parsed data.

Thus adding proposed functionality would be IMHO much more problematic than adding simple `[main]` section to the beginning of the ini file.

Maybe you will find some elegant solution how to implement this functionality without breaking backward compatibility (e.g. new subclass of `ConfigParser`). We accept pull requests.

Thanks

Jiri

**Comment by Somebodyisnobody** [comment]
Okay thanks for your answer. Now I understand why section are required for parsing. Unfortunally I've no experience with python so for now I'll try it by adding a dummy-section.

If anybody has time and want's to (and can) implement that, I'ld suggest adding a boolean to the parse-functions which causes iniparse to add such a dummy-section as first line of the file internally before parsing. This could then result in:
`print cfg.dummy.key`
