### ISSUE TITLE
Dead code in RawConfigParser.get

### ISSUE THREAD

**Issue by adelton** [candlepin/python-iniparse#2]
This parser is packaged in Fedora as python3-iniparse-0.4-32.fc29.noarch and used by dnf for which I'm currently writing some plugin code. I was looking at the sources, hoping to find a way to provide default values to `.get()`, to avoid having the `configparser.NoOptionError` exception raised.

Looking at https://github.com/candlepin/python-iniparse/blob/d336b8d7ac0c546815aeae0d0c3ecc24228e6ff0/iniparse/compat.py#L118-L125 I'm surprised that value is assigned to `value` with `value = vars[option]` but `value` then does not seem to be used at all. And it then looks like `vars` is not used at all either.

Could you clarify what the code does, or remove it?

**Comment by jirihnidek** [comment]
Hi,
thanks for the issue. Yeah. It seems that the code full of dead code. I'm just cleaning it.

**Comment by jirihnidek** [comment]
Fixed in #6
