### ISSUE TITLE
New release for official python>=3.11 compatibility

### ISSUE THREAD

**Issue by tosky** [candlepin/python-iniparse#26]
Since 0.5, the code gained python 3.11 compatibility and other fixes, so maybe it's time for a new release?

If that's the case, setup.py should be updated to drop python 2 and add the newer python releases as supported.

(ok, there is also a patch from yours truly in between the changes, but that's not the important bit here :)

**Comment by a-detiste** [comment]
Hi, Py2 is already gone: https://github.com/candlepin/python-iniparse/pull/25

Please publish a new release to help global `six` removal and track stragling packages.

Greetings

**Comment by yselkowitz** [comment]
Fedora's package failed to build with the Python 3.12 mass rebuild because the latest release does not include the fixes in question.  While they could be backported, a new release (which appears much overdue anyways) would be much easier.

**Comment by tosky** [comment]
Hello, any news about a new release?

**Comment by a-detiste** [comment]
ping

**Comment by jirihnidek** [comment]
I created new release https://github.com/candlepin/python-iniparse/releases/tag/0.5.1 this release has support for Python3.11 Python3.12 and Python3.13. For this reason I'm closing this issue.
