### ISSUE TITLE
Update PyPi Release

### ISSUE THREAD

**Issue by KyleKing** [candlepin/python-iniparse#5]
Would you consider publishing this package to PyPi for `pip install ...`?

**Comment by jhasse** [comment]
Isn't available as `pip install iniparse`? (I think you need Python 3)

**Comment by KyleKing** [comment]
Oh I see. I thought this repository was a fork (there are so many). I think my firewall initially blocked the redirect from [Google Code](https://code.google.com/archive/redirect/a/code.google.com/p/iniparse?movedTo=https:%2F%2Fgithub.com%2Fcandlepin%2Fpython-iniparse), which would otherwise redirects to this repository.

The published PyPi package just needs to be updated. The wheel file is from the [2010 v0.4 release](https://pypi.org/project/iniparse/0.4/#files), but the Python3 improvements [were made in 2018](https://github.com/candlepin/python-iniparse/commit/9ea31e4d1267dd620814eceffabb5b7457ea9fae)

I double checked the source code installed to site-packages. The below contents are from `./Lib/site-packages/iniparse/__ini__.py`, which should have the relative import statements from the [Python3 version on Github](https://github.com/candlepin/python-iniparse/blob/master/iniparse/__init__.py). (i.e. should be `from .ini import ...`)

```py
# Copyright (c) 2001, 2002, 2003 Python Software Foundation
# Copyright (c) 2004-2008 Paramjit Oberoi <param.cs.wisc.edu>
# Copyright (c) 2007 Tim Lauridsen <tla@rasmil.dk>
# All Rights Reserved.  See LICENSE-PSF & LICENSE for details.

from ini import INIConfig, change_comment_syntax
from config import BasicConfig, ConfigNamespace
from compat import RawConfigParser, ConfigParser, SafeConfigParser
from utils import tidy

from ConfigParser import DuplicateSectionError,    \
                  NoSectionError, NoOptionError,   \
                  InterpolationMissingOptionError, \
                  InterpolationDepthError,         \
                  InterpolationSyntaxError,        \
                  DEFAULTSECT, MAX_INTERPOLATION_DEPTH

__all__ = [
    'BasicConfig', 'ConfigNamespace',
    'INIConfig', 'tidy', 'change_comment_syntax',
    'RawConfigParser', 'ConfigParser', 'SafeConfigParser',
    'DuplicateSectionError', 'NoSectionError', 'NoOptionError',
    'InterpolationMissingOptionError', 'InterpolationDepthError',
    'InterpolationSyntaxError', 'DEFAULTSECT', 'MAX_INTERPOLATION_DEPTH',
]
```

---

In Python3

```
(py372) > pip install iniparse
Collecting iniparse
  Using cached https://files.pythonhosted.org/packages/0f/d1/3090ef9be165da5ddb1b0cf2b332d3282588bdd2dd0967e94b547f10055f/iniparse-0.4.tar.gz
Building wheels for collected packages: iniparse
  Running setup.py bdist_wheel for iniparse ... done
  Stored in directory: C:\Users\king.kyle\AppData\Local\pip\Cache\wheels\93\dd\d3\b5174b8df32caf36ffb5e78a577c6c5e1676a7366dcd528381
Successfully built iniparse
Installing collected packages: iniparse
Successfully installed iniparse-0.4

(py372) > python
Python 3.7.2 (default, Jan  2 2019, 17:27:13) [MSC v.1912 32 bit (Intel)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import iniparse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\king.kyle\AppData\Local\Continuum\anaconda2\envs\py372\lib\site-packages\iniparse\__init__.py", line 6, in <module>
    from ini import INIConfig, change_comment_syntax
ModuleNotFoundError: No module named 'ini'
>>>
```

In Python2:

```
(base) > python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:12) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import iniparse
>>>
```

**Comment by razorsedge** [comment]
Updating PyPi is needed to fix a dependency of pixelb/crudini#58

**Comment by jirihnidek** [comment]
Hi All,
thanks for interest. I just asked if I could be added as maintainer of https://pypi.org/project/iniparse/. Paramjit Oberoi (author of iniparse) was helpful in past so I hope that he will be helpful again. When I will be maintainer of the project, then I can update pypi project.

**Comment by aoshiken** [comment]
@jirihnidek 
as of today it seems that you're already the maintaner of the project so would you be so kind to update the PyPi version?

Thanks in advance

**Comment by jirihnidek** [comment]
@aoshiken I just created new release of iniparse (0.5). Check it here: https://pypi.org/project/iniparse/ ... I tested it using pipenv with Python 2.7 and Python 3.6 and it seems that it works as expected.

**Comment by KyleKing** [comment]
Tested on Python 3.7 and works for me as well. Thanks!
